### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by fen328199260** [alex-sage/logo-gen#1]
[warren@cernet dcgan]$ python main.py 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from model import DCGAN
  File "/home/warren/logo-gen-master/dcgan/model.py", line 11, in <module>
    from utils import *
  File "/home/warren/logo-gen-master/dcgan/utils.py", line 22, in <module>
    import file_handling as fh
ImportError: No module named file_handling

There are some files missing from your project. I find them are listed in the  [.gitignore](https://github.com/alex-sage/logo-gen/blob/05e98b99d5368be64f98e3ac74ce5e0284d55aef/dcgan/.gitignore#L91), could you please upload those files? thanks.

**Comment by alex-sage** [comment]
Hi, thanks for pointing this out to me.
"file_handling" is actually an old module which is not used in the current code. You should be able to simply comment out line 22 in utils.py to get rid of the error. Sorry for this oversight, I'll correct the code in the repo right away.
If you run into any other difficulties, please let me know.

**Comment by alex-sage** [comment]
I just noticed that the metrics module is in fact still used, and uploaded the respective file. Again, if you notice any more problems, please let me know.

**Comment by fen328199260** [comment]
Thanks for your code. I have found some new problems:
1. the parameter [sigma](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/main.py#L40)  does not seem to be used in the code and the type may be float.
2. the parameter [sample_dir](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/main.py#L93) is not available in the [WGAN](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/model.py#L16) initialization list.
3. two parameters are required [here](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/model.py#L279), but the [function](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/wgan/tflib/hdf5_images.py#L34) only returns one parameter.
4. [sample_images](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/model.py#L395)  needs to be transposed ( sample_images = sample_images.transpose((0,2,3,1)) ) before inputting the generator.

By the way, which version of tensorflow are you using to run this code?

**Comment by alex-sage** [comment]
Hi, sorry for not addressing your issues... I didn't have a lot of time on my hands so I seem to have completely forgotten about it.

For the record (even though I'd assume you don't need it any more):
1. This parameter is only used when using truncated gaussian sampling. It is read [here](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/model.py#L168). You're correct however that it should be of type float (I never really used truncated gaussian so I never noticed I guess).
2. This is strange indeed. Seems to be some haphazard refactoring... I'll remove it from the constructor call.
3. The function you linked to returns `make_generator()` defined right above it, which in turn returns `get_epoch()` which [yields](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/wgan/tflib/hdf5_images.py#L22) the tuple `(images, labels)`. So no issue here.
4. Yes you're right, they have to for my datasets. My wgan implementation uses NCHW, so there they're in the right format, didn't think about that when simply linking to the data generator. Thanks for pointing this out.

DCGAN runs with the same tensorflow version as the [original implementation](https://github.com/carpedm20/DCGAN-tensorflow) (Tensorflow 0.12.1) however it was tested and should be compatible with at least up to TF 1.3 if I recall correctly.

**Comment by fen328199260** [comment]
Thanks for your reply, and also apologize for that I did not describe the third point clearly. The function [load ](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/wgan/tflib/hdf5_images.py#L26) returns a function address, but when you try to [call ](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/dcgan/model.py#L279)the function [load ](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/wgan/tflib/hdf5_images.py#L26), you not only want to get the address but also the number of images, so I guess that [output parameters](https://github.com/alex-sage/logo-gen/blob/fafea5795f0e2c655f215f426b2a22f983cf3d9a/wgan/tflib/hdf5_images.py#L34) of the function load should be `return make_generator(hdf5_file, n_images, batch_size, res=resolution, label_name=label_name), n_images `.
