### ISSUE TITLE
Unable to load checkpoints to DCGAN architecture for inference purposes

### ISSUE THREAD

**Issue by jmtzt** [alex-sage/logo-gen#17]
Hello there, it seems that whatever I try to change in the code I can't find out why the checkpoints could not be loaded properly. 

discriminator/d_h3_lin/bias:0 (float32_ref 1) [1, bytes: 4]
Total size of variables: 9451908
Total bytes of variables: 37807632
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [*] 0
Traceback (most recent call last):
  File "C:\Users\Joao Marcelo\Anaconda3\envs\oficinaintegracao\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\Joao Marcelo\Anaconda3\envs\oficinaintegracao\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Joao Marcelo\Anaconda3\envs\oficinaintegracao\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value generator/g_h4/b
         [[{{node generator/g_h4/b/read}}]]
         [[concat_3/_5]]
  (1) Failed precondition: Attempting to use uninitialized value generator/g_h4/b
         [[{{node generator/g_h4/b/read}}]]
0 successful operations.
0 derived errors ignored.

**Comment by HymEric** [comment]
@jmtzt Do you know how to do inference with the pretrained model?
