### ISSUE TITLE
Run inception_score.py  and got an ValueError problem

### ISSUE THREAD

**Issue by kawsor** [alex-sage/logo-gen#2]
Traceback (most recent call last):
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1626, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2048], [2048,1008].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kawsorandy/TensorFlow/WGAN/tflib/inception_score.py", line 96, in <module>
    _init_inception()
  File "/Users/kawsorandy/TensorFlow/WGAN/tflib/inception_score.py", line 92, in _init_inception
    logits = tf.matmul(tf.squeeze(pool3), w)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2053, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4560, in mat_mul
    name=name)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1790, in __init__
    control_input_ops)
  File "/anaconda2/envs/untitled/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1629, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2048], [2048,1008].

Process finished with exit code 1

**Comment by alex-sage** [comment]
For future reference: This happens if you try to run the network with a wrong TF version. Try tensorflow 1.3.0 which it has been tested for.

**Comment by kdy1** [comment]
@alex-sage I hit this error with tensorflow 1.3.0 (cpu)
I could not install tensorflow-gpu==1.3.0 because old cuda library file does not exist.

```
>>> tf.__version__
'1.3.0'
```
---

Changing to
```python3
        logits = tf.matmul(tf.squeeze(pool3, [1, 2]), w)
```

fixes the issue
